# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title/

# Setup
title:            'Ashish Dasnurkar'
tagline:          'Full stack developer'
description:      ''
url:              http://ashishdasnurkar.com
baseurl:          /

author:
  name:           'Ashish Dasnurkar'
  url:            https://twitter.com/ashishdasnurkar

paginate:         5

pages_list:       
  Who am I?: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ashishdasnurkar/ashishdasnurkar.github.io
